### ISSUE TITLE
off topic: you hear anything about these in your area?

### ISSUE THREAD

**Issue by mrose17** [CloCkWeRX/node-samsung-airconditioner#3]
http://global.samsungtomorrow.com/?p=35413

**Comment by CloCkWeRX** [comment]
'fraid not! I did however get ninjablocks today, so even if they do appear
my attention might be scant,....

**Comment by mrose17** [comment]
thanks. no worries. apparently samsung isn't doing much of a roll-out in the US, which is sad… but if you see cool stuff from them, please let me know... thanks!
